include ../Makefile.kernel




d:
	pintos -v -k -T 10 --qemu -- -q run priority-condvar
f:
	pintos -v -k -T 10 --qemu -- -q run priority-sema


res:
	make clean
	make check
t:
	vim thread.c
s:
	vim synch.c
m:
	vim Makefile



